apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-note-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: formazionesou.local 
    http:
      paths:
      - path: / 
        pathType: Prefix 
        backend: 
          service:
            name: app-note-service 
            port: 
              number: 80